before_install:
  - gem update bundler
  - bundle --version
  - gem update --system
  - gem --version
bundler_args: --without development
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx
  - ruby-head
